# Generated by Django 3.2 on 2021-06-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='for_anonymous_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.BooleanField(default=False, verbose_name='скидка'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Скидочная цена'),
        ),
        migrations.DeleteModel(
            name='Specifications',
        ),
    ]
